In [3]:
import numpy as np
import pandas as pd
import pickle
from sklearn.tree import DecisionTreeRegressor

def price_estimator(features):
    with open('Model.sav', 'rb') as f:
        model = pickle.load(f)
    return model.predict(features)

In [4]:
features = np.array([445,318,4324,5025,154,0,1214,6183,7096,43,74,100,210,3118,29014,283,283,283,1036,84,5,256,0,275,275,275,1036,87,1,196,16,271,271,271,1005,75,1,224,0,280,280,280,1038,78,2,45,0,275,275,275,1021,81,1,220,0,2015,1,1,19])
features

array([  445,   318,  4324,  5025,   154,     0,  1214,  6183,  7096,
          43,    74,   100,   210,  3118, 29014,   283,   283,   283,
        1036,    84,     5,   256,     0,   275,   275,   275,  1036,
          87,     1,   196,    16,   271,   271,   271,  1005,    75,
           1,   224,     0,   280,   280,   280,  1038,    78,     2,
          45,     0,   275,   275,   275,  1021,    81,     1,   220,
           0,  2015,     1,     1,    19])

In [5]:
price_estimator(features.reshape(1, -1))

array([75.64])

In [6]:
price = price_estimator(features.reshape(1, -1))
price

array([75.64])

In [7]:
price[0]

75.64

In [8]:
type(price[0])

numpy.float64

In [9]:
75.64

75.64